//Auto Generated by 'npm run gen-icon-index'
import { exportToGlobal } from '../../../utils';
import { AzIcon } from '../az-icon';

import Android from './android';
import ArrowDown from './arrow-down';
import ArrowLeft from './arrow-left';
import ArrowRight from './arrow-right';
import ArrowUp from './arrow-up';
import Backward from './backward';
import Bars from './bars';
import Book from './book';
import Check from './check';
import CircleCheck from './circle-check';
import CircleCross from './circle-cross';
import CircleExclamation from './circle-exclamation';
import Close from './close';
import Cog from './cog';
import Cogs from './cogs';
import Copy from './copy';
import Debian from './debian';
import DirTree from './dir-tree';
import Download from './download';
import Drag from './drag';
import Edit from './edit';
import EllipsisH from './ellipsis-h';
import EllipsisV from './ellipsis-v';
import EmptyBox from './empty-box';
import Exchange from './exchange';
import Exclamation from './exclamation';
import Eye from './eye';
import EyeClose from './eye-close';
import FastBackward from './fast-backward';
import FastForward from './fast-forward';
import Fedora from './fedora';
import File from './file';
import FloppyDisk from './floppy-disk';
import Folder from './folder';
import Forward from './forward';
import Heart from './heart';
import Linux from './linux';
import List from './list';
import Loading from './loading';
import Logout from './logout';
import Mac from './mac';
import Minus from './minus';
import MousePointer from './mouse-pointer';
import Move from './move';
import MoveNodeDown from './move-node-down';
import MoveNodeUp from './move-node-up';
import NewChildNode from './new-child-node';
import NewSiblingNode from './new-sibling-node';
import NintendoSwitch from './nintendo-switch';
import OpenFolder from './open-folder';
import Paste from './paste';
import Pause from './pause';
import Plus from './plus';
import Question from './question';
import Redhat from './redhat';
import Redo from './redo';
import Refresh from './refresh';
import Search from './search';
import Share from './share';
import Share2 from './share2';
import ShopCart from './shop-cart';
import Square from './square';
import SuseLinux from './suse-linux';
import ThreeDots from './three-dots';
import Trash from './trash';
import Triangle from './triangle';
import Ubuntu from './ubuntu';
import Undo from './undo';
import Windows from './windows';
import ZoomIn from './zoom-in';
import ZoomOut from './zoom-out';
const builtinIcons: Record<string, string | string[]> = {
  "android": Android,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "backward": Backward,
  "bars": Bars,
  "book": Book,
  "check": Check,
  "circle-check": CircleCheck,
  "circle-cross": CircleCross,
  "circle-exclamation": CircleExclamation,
  "close": Close,
  "cog": Cog,
  "cogs": Cogs,
  "copy": Copy,
  "debian": Debian,
  "dir-tree": DirTree,
  "download": Download,
  "drag": Drag,
  "edit": Edit,
  "ellipsis-h": EllipsisH,
  "ellipsis-v": EllipsisV,
  "empty-box": EmptyBox,
  "exchange": Exchange,
  "exclamation": Exclamation,
  "eye": Eye,
  "eye-close": EyeClose,
  "fast-backward": FastBackward,
  "fast-forward": FastForward,
  "fedora": Fedora,
  "file": File,
  "floppy-disk": FloppyDisk,
  "folder": Folder,
  "forward": Forward,
  "heart": Heart,
  "linux": Linux,
  "list": List,
  "loading": Loading,
  "logout": Logout,
  "mac": Mac,
  "minus": Minus,
  "mouse-pointer": MousePointer,
  "move": Move,
  "move-node-down": MoveNodeDown,
  "move-node-up": MoveNodeUp,
  "new-child-node": NewChildNode,
  "new-sibling-node": NewSiblingNode,
  "nintendo-switch": NintendoSwitch,
  "open-folder": OpenFolder,
  "paste": Paste,
  "pause": Pause,
  "plus": Plus,
  "question": Question,
  "redhat": Redhat,
  "redo": Redo,
  "refresh": Refresh,
  "search": Search,
  "share": Share,
  "share2": Share2,
  "shop-cart": ShopCart,
  "square": Square,
  "suse-linux": SuseLinux,
  "three-dots": ThreeDots,
  "trash": Trash,
  "triangle": Triangle,
  "ubuntu": Ubuntu,
  "undo": Undo,
  "windows": Windows,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
};
export default builtinIcons;
exportToGlobal('icons', {
  get() {
    return Object.keys(AzIcon.icons);
  }
})
// for Demo
/*
  <az-icon icon="android" title="android" hover-effect="border"></az-icon>
  <az-icon icon="arrow-down" title="arrow-down" hover-effect="border"></az-icon>
  <az-icon icon="arrow-left" title="arrow-left" hover-effect="border"></az-icon>
  <az-icon icon="arrow-right" title="arrow-right" hover-effect="border"></az-icon>
  <az-icon icon="arrow-up" title="arrow-up" hover-effect="border"></az-icon>
  <az-icon icon="backward" title="backward" hover-effect="border"></az-icon>
  <az-icon icon="bars" title="bars" hover-effect="border"></az-icon>
  <az-icon icon="book" title="book" hover-effect="border"></az-icon>
  <az-icon icon="check" title="check" hover-effect="border"></az-icon>
  <az-icon icon="circle-check" title="circle-check" hover-effect="border"></az-icon>
  <az-icon icon="circle-cross" title="circle-cross" hover-effect="border"></az-icon>
  <az-icon icon="circle-exclamation" title="circle-exclamation" hover-effect="border"></az-icon>
  <az-icon icon="close" title="close" hover-effect="border"></az-icon>
  <az-icon icon="cog" title="cog" hover-effect="border"></az-icon>
  <az-icon icon="cogs" title="cogs" hover-effect="border"></az-icon>
  <az-icon icon="copy" title="copy" hover-effect="border"></az-icon>
  <az-icon icon="debian" title="debian" hover-effect="border"></az-icon>
  <az-icon icon="dir-tree" title="dir-tree" hover-effect="border"></az-icon>
  <az-icon icon="download" title="download" hover-effect="border"></az-icon>
  <az-icon icon="drag" title="drag" hover-effect="border"></az-icon>
  <az-icon icon="edit" title="edit" hover-effect="border"></az-icon>
  <az-icon icon="ellipsis-h" title="ellipsis-h" hover-effect="border"></az-icon>
  <az-icon icon="ellipsis-v" title="ellipsis-v" hover-effect="border"></az-icon>
  <az-icon icon="empty-box" title="empty-box" hover-effect="border"></az-icon>
  <az-icon icon="exchange" title="exchange" hover-effect="border"></az-icon>
  <az-icon icon="exclamation" title="exclamation" hover-effect="border"></az-icon>
  <az-icon icon="eye" title="eye" hover-effect="border"></az-icon>
  <az-icon icon="eye-close" title="eye-close" hover-effect="border"></az-icon>
  <az-icon icon="fast-backward" title="fast-backward" hover-effect="border"></az-icon>
  <az-icon icon="fast-forward" title="fast-forward" hover-effect="border"></az-icon>
  <az-icon icon="fedora" title="fedora" hover-effect="border"></az-icon>
  <az-icon icon="file" title="file" hover-effect="border"></az-icon>
  <az-icon icon="floppy-disk" title="floppy-disk" hover-effect="border"></az-icon>
  <az-icon icon="folder" title="folder" hover-effect="border"></az-icon>
  <az-icon icon="forward" title="forward" hover-effect="border"></az-icon>
  <az-icon icon="heart" title="heart" hover-effect="border"></az-icon>
  <az-icon icon="linux" title="linux" hover-effect="border"></az-icon>
  <az-icon icon="list" title="list" hover-effect="border"></az-icon>
  <az-icon icon="loading" title="loading" hover-effect="border"></az-icon>
  <az-icon icon="logout" title="logout" hover-effect="border"></az-icon>
  <az-icon icon="mac" title="mac" hover-effect="border"></az-icon>
  <az-icon icon="minus" title="minus" hover-effect="border"></az-icon>
  <az-icon icon="mouse-pointer" title="mouse-pointer" hover-effect="border"></az-icon>
  <az-icon icon="move" title="move" hover-effect="border"></az-icon>
  <az-icon icon="move-node-down" title="move-node-down" hover-effect="border"></az-icon>
  <az-icon icon="move-node-up" title="move-node-up" hover-effect="border"></az-icon>
  <az-icon icon="new-child-node" title="new-child-node" hover-effect="border"></az-icon>
  <az-icon icon="new-sibling-node" title="new-sibling-node" hover-effect="border"></az-icon>
  <az-icon icon="nintendo-switch" title="nintendo-switch" hover-effect="border"></az-icon>
  <az-icon icon="open-folder" title="open-folder" hover-effect="border"></az-icon>
  <az-icon icon="paste" title="paste" hover-effect="border"></az-icon>
  <az-icon icon="pause" title="pause" hover-effect="border"></az-icon>
  <az-icon icon="plus" title="plus" hover-effect="border"></az-icon>
  <az-icon icon="question" title="question" hover-effect="border"></az-icon>
  <az-icon icon="redhat" title="redhat" hover-effect="border"></az-icon>
  <az-icon icon="redo" title="redo" hover-effect="border"></az-icon>
  <az-icon icon="refresh" title="refresh" hover-effect="border"></az-icon>
  <az-icon icon="search" title="search" hover-effect="border"></az-icon>
  <az-icon icon="share" title="share" hover-effect="border"></az-icon>
  <az-icon icon="share2" title="share2" hover-effect="border"></az-icon>
  <az-icon icon="shop-cart" title="shop-cart" hover-effect="border"></az-icon>
  <az-icon icon="square" title="square" hover-effect="border"></az-icon>
  <az-icon icon="suse-linux" title="suse-linux" hover-effect="border"></az-icon>
  <az-icon icon="three-dots" title="three-dots" hover-effect="border"></az-icon>
  <az-icon icon="trash" title="trash" hover-effect="border"></az-icon>
  <az-icon icon="triangle" title="triangle" hover-effect="border"></az-icon>
  <az-icon icon="ubuntu" title="ubuntu" hover-effect="border"></az-icon>
  <az-icon icon="undo" title="undo" hover-effect="border"></az-icon>
  <az-icon icon="windows" title="windows" hover-effect="border"></az-icon>
  <az-icon icon="zoom-in" title="zoom-in" hover-effect="border"></az-icon>
  <az-icon icon="zoom-out" title="zoom-out" hover-effect="border"></az-icon>
*/
